### ISSUE TITLE
issue in  RTL layout Direction

### ISSUE THREAD

**Issue by snbanitaba** [diegodobelo/AndroidExpandingViewLibrary#1]
when i using expanding list in rtl layput direction its not shown items text and add icons and sub items texts. what i do ? 

![untitled](https://cloud.githubusercontent.com/assets/20625576/17084138/cff21334-51cb-11e6-8d54-703a6ffb43fa.jpg)

**Comment by diegodobelo** [comment]
Hi. RTL is not supported yet. I'll implement it and let you know.

**Comment by diegodobelo** [comment]
@snbanitaba RTL is working now on version 0.9.2.
Thank you very much for your feedback.
