### ISSUE TITLE
Is it possible to make this nice library fully RTL?

### ISSUE THREAD

**Issue by HadiAghandeh** [diegodobelo/AndroidExpandingViewLibrary#10]
I need to locate the icon at the right side of the screen and locate the text at the left side of the icon. is this possible?

**Comment by diegodobelo** [comment]
Hi @hadiaec20h , this library supports RTL. Please run the example app available in this repository and change the device language to a RTL language.
![device-2017-05-13-211119](https://cloud.githubusercontent.com/assets/4092717/26030173/1742698c-3821-11e7-82fe-525f1aafb2f8.png)

If you have any other doubts, just ask.

**Comment by pishguy** [comment]
@diegodobelo 

commenting for @hadiaec20h user as:

> I need to locate the icon at the right side of the screen and locate the text at the left side of the icon. is this possible?

that means support RTL when device language is english or LTR

**Comment by pishguy** [comment]
@hadiaec20h you must download source code and try to change your self
