### ISSUE TITLE
How to create another list inside child item

### ISSUE THREAD

**Issue by VinitSandesara** [diegodobelo/AndroidExpandingViewLibrary#11]
Is it possible to create another list (String array) inside child item on click ? Like in this example

- Mary
----- Dog
----------- Has 4 log (how to add this inside Dog on click)

Thanks
Vinit

**Comment by venkataramanaduddu** [comment]
Hi, if u done this can u share the code.

**Comment by diegodobelo** [comment]
Hi @venkataramanaduddu and @VinitSandesara 
This version of this library does not support a third level of items.
I'll consider to add this feature in a future release.
