### ISSUE TITLE
How to replace the old data of expandingList?

### ISSUE THREAD

**Issue by ShineYang** [diegodobelo/AndroidExpandingViewLibrary#2]
How to replace the old data of expandingList? I called method expandingList.removeAllViews(),it doesn't work.That's not like listview cuz the view was extended from scrollview,so I can't find a good idea to replace the old data.Can you help me ? Thanx

**Comment by diegodobelo** [comment]
Hi. There is not method to remove all items yet. I'll implement it and let you know.

**Comment by ShineYang** [comment]
Okay, thanx.

**Comment by diegodobelo** [comment]
I implemented two methods in ExpandingList class: removeItem and removeAllViews.
I also updated the example code to have an icon to remove an item.
