### ISSUE TITLE
Suggestion: Embed the YouTube video to the readme / Add screenshots

### ISSUE THREAD

**Issue by MarkOSullivan94** [diegodobelo/AndroidExpandingViewLibrary#3]
I think it'd be better if you would embed the YouTube video to the readme or add screenshots instead of just having a link to the YouTube video.

Whenever I look over libraries, I like to be able to quickly see what the library looks like before using it.

**Comment by deshario** [comment]
Ya ! Sure I think everybody should look UI First or wants to know actually how the library looks like ! before they use it ... If there's no example,guidlines, even library is superb ..... people dont use it  because of lacking information guidlines ! Thankx

**Comment by tamzi** [comment]
@MarkOSullivan94 @deshario @diegodobelo Solved it...see above

**Comment by diegodobelo** [comment]
Thanks @tamzi
