### ISSUE TITLE
SubExpandingList inside ExpandingList?

### ISSUE THREAD

**Issue by willu2** [diegodobelo/AndroidExpandingViewLibrary#5]
Can create SubExpandingList inside ExpandingList?
Or ExpandingItem inside ExpandingItem?

**Comment by diegodobelo** [comment]
Hi. What do you want to achieve with this?
Could you please provide more details or a sample code?
Thanks.

**Comment by willu2** [comment]
Thanks for your response. I need expanding list inside another expanding list.  It is like Three Level ListView in ExpandableListView. Or like this:
![buifc](https://cloud.githubusercontent.com/assets/5244992/21473178/36f58f44-cb06-11e6-86c5-1d99163d4d0d.png)

In Two level your code works perfectly well.

**Comment by diegodobelo** [comment]
Sorry @willu2 , that is not possible to do in the current version of this library. It would require a lot of changes in the code.
I'll take it as a suggestion fot the next version.
